### ISSUE TITLE
DockerFile - tasks and config folders are hardcode

### ISSUE THREAD

**Issue by KnightDoom** [BaldissaraMatheus/Tasks.md#113]
the Docker file provides an ENV variable to allow setting the path_to_config and path_to_tasks directories.

```
ENV CONFIG_DIR="/config"
ENV TASKS_DIR="/tasks"
```
However the Entry point does not consider this and hardcodes it in the chown commands
```
ENTRYPOINT mkdir -p /config/stylesheets/ && \
	mkdir -p /config/images/ && \
	mkdir -p /config/sort/ && \
	cp -r /config/stylesheets/. /stylesheets/ && \
	cp -r /stylesheets/. /config/stylesheets/ && \
	chown -R $PUID:$PGID /config && \
	chown -R $PUID:$PGID /tasks && \
	node /api/server.js
```

**Comment by BaldissaraMatheus** [comment]
Fixed by #116

**Comment by BaldissaraMatheus** [comment]
Reopened as I couldn't finish the changes I wanted for the next release. Added a new tag to track it properly.

**Comment by BaldissaraMatheus** [comment]
Fix included in the latest release
