### ISSUE TITLE
Add an option to render Checklist in markdown

### ISSUE THREAD

**Issue by cgupta98** [BaldissaraMatheus/Tasks.md#115]
i was trying to create a checklist in markdown using this:

### Solar System Exploration, 1950s – 1960s

- [ ] Mercury
- [x] Venus
- [ ] Comet Haley
- [x] Earth (Orbit/Moon)
- [x] Mars
- [ ] Jupiter
- [ ] Saturn
- [ ] Uranus
- [ ] Neptune

but this is not rendering as a checklist in the notes

**Comment by cgupta98** [comment]
![image](https://github.com/user-attachments/assets/55bec9c1-efc7-4728-bc3d-788c65693586)

**Comment by BaldissaraMatheus** [comment]
I'll be closing this one because it's already reported on #76
It's a high priority issue and I plan to deliver it for the next release
