### ISSUE TITLE
Cards can only be moved when manual sorting is active

### ISSUE THREAD

**Issue by sir-andreas** [BaldissaraMatheus/Tasks.md#118]
Hi, 

In my tasks.md installation  I only can move cards when sorting is set to "Manually". 
![image](https://github.com/user-attachments/assets/fb0d88cb-585c-45f2-a808-ba60ee4ed069)

For all other options drag and drop seems to be disabled somehow. My understanding is, that with fixed sorting a move of cards between columns should still be possible, correct?

Thanks and BR

**Comment by BaldissaraMatheus** [comment]
To be honest I didn't paid attention to this detail and simply disabled the card so you can't sort them. But you're right, it should be possible to move them between lanes. I'm planning to submit a new release this week, so I'll try to include the fix for this issue too

**Comment by sir-andreas** [comment]
thanks for the quick reaction and this great piece of software, as well!

**Comment by BaldissaraMatheus** [comment]
Implemented on #119. I'm going to publish the new release with the fix in a few minutes. If you encounter a problem related to the solution feel free to open the issue again
