### ISSUE TITLE
Maintain on-disk edits to markdown files while app is running

### ISSUE THREAD

**Issue by benjaminapetersen** [BaldissaraMatheus/Tasks.md#142]
Quick test, if you edit a markdown file in a code editor, then load it via tasks.md, your edits will be lost. 
Perhaps tasks.md can always reload from disk, at least once the task (in browser) is closed & not being actively edited?

**Comment by BaldissaraMatheus** [comment]
Related to #111 I think

**Comment by benjaminapetersen** [comment]
Definitely!

**Comment by benjaminapetersen** [comment]
Prob can close as duplicate.
