### ISSUE TITLE
Preview in Dark Mode not readable

### ISSUE THREAD

**Issue by kernelkaribou** [BaldissaraMatheus/Tasks.md#17]
### Issue
When previewing the description of a task  in dark mode it will be all white and unreadable

Preview NOT selected
![image](https://user-images.githubusercontent.com/25406580/225382631-39ccb58c-72c2-456c-bab2-a10048ebad79.png)

Preview selected
![image](https://user-images.githubusercontent.com/25406580/225382757-76d9bbe6-6111-4ad0-b18b-d2021afb520b.png)

### Steps to Reproduce
Setting theme to dark mode, start writing a description and switch to preview mode.

### Other
Thanks for this project.

Version 1.3

**Comment by BaldissaraMatheus** [comment]
Thanks for reporting the issue @kernelkaribou, I just merged a PR that fixes this bug. If you verify that the issue still persists, please open it again
