### ISSUE TITLE
Search filter descriptions or Tags

### ISSUE THREAD

**Issue by kernelkaribou** [BaldissaraMatheus/Tasks.md#23]
### Feature Request

I believe it would be a great enhancement to be able to not only search by the tasks title, but also the description. When you think of extensive descriptions, to be able to filter tasks for 'keywords' would be nice. I understand that tags could be used to help call out certain details of a tasks or at least be able to find all my "administrative" tasks or similar, however looks like tags don't even get looked at in search. At the very least Tag search filtering would be beneficial if not the whole description.

Thanks.

**Comment by BaldissaraMatheus** [comment]
Thanks for the suggestion, just included this feature
