### ISSUE TITLE
Seeing a "Not Found" page.

### ISSUE THREAD

**Issue by Entheologian** [BaldissaraMatheus/Tasks.md#29]
Hi,

Using docker-compose.yml:
version: '3.3'
services:
    tasks.md:
        container_name: tasks.md
        image: baldissaramatheus/tasks.md
        ports:
            - 8383:8080
        volumes:
            - ./cards:/api/files
            - ./styles:/usr/share/nginx/html/stylesheets
        environment:
            - TZ=America/Toronto
            - PGID=1000
            - PUID=1000
            - TITLE="My tasks board"
            - BASE_PATH=/tasks
        restart: unless-stopped

Start-up only shows this:
Creating network "tasksmd_default" with the default driver
Creating tasks.md ... done
Attaching to tasks.md
tasks.md    | 

When I connect to http://host:8383 I see only "Not Found". It used to work, but I think it stopped about a day or so ago. Is there something else I can try?

**Comment by BaldissaraMatheus** [comment]
Its probably because you set the BASE_PATH variable as /tasks, so the app is running on http://host:8383/tasks.
Try opening http://host:8383/tasks and check if it works. If you want to run it without the /tasks path you have to remove that variable from your docker-compose file

**Comment by Entheologian** [comment]
Marking as closed - issue resolved due to my incorrect local changes..

**Comment by BaldissaraMatheus** [comment]
Great! I'll close then
