### ISSUE TITLE
[Enhancement] Add favicon

### ISSUE THREAD

**Issue by mckennapl** [BaldissaraMatheus/Tasks.md#31]
I love this app and use it frequently, but looks a bit bland in my bookmark menu without a favicon. Any chance one is planned on being added in a future release? Fwiw the pen emoji would be a-ok.

**Comment by BaldissaraMatheus** [comment]
Yeah, I think it feels a little amateur-ish not having a favicon. I included the pen emoji while it doesn't have a proper one, but it's definitely not the best solution. So yeah, it's definitely something that will be included in the future

**Comment by BaldissaraMatheus** [comment]
Just turned the pen emoji into an actual favicon, but I'll keep this thread open because I think it could have something better

**Comment by mms-gianni** [comment]
The pen looks nice. 

I helped another FOSS project to find an icon/logo and used midjourney. You'll find some prompts in the linked issue. It might still need some work to get a SVG out of it. 

https://github.com/Frooodle/Stirling-PDF/issues/15

**Comment by BaldissaraMatheus** [comment]
New logo added in #65
