### ISSUE TITLE
Not found issue

### ISSUE THREAD

**Issue by psagat** [BaldissaraMatheus/Tasks.md#35]
After starting the container via docker compose and accessing it via url all I get is a "not found" message on the site. Logs are empty and dont indicate what the issue could be.

**Comment by BaldissaraMatheus** [comment]
Could you share your docker-compose file and the exactly url you're trying to access?

**Comment by psagat** [comment]
It's the docker compose example given but the port changed to 8282.

Http://docker:8282

**Comment by psagat** [comment]
Oh shoot I should have paid more attention. That was it, thanks.

**Comment by BaldissaraMatheus** [comment]
Great! I'm glad it worked. I'm closing this thread now
