### ISSUE TITLE
Be able to change tag colors

### ISSUE THREAD

**Issue by BaldissaraMatheus** [BaldissaraMatheus/Tasks.md#4]
**Description**
Right now all the tags have the same background color, it would be nice if each tag had a different color so they could be easily identified

**Version**
1.1.0

**Comment by AlexKalopsia** [comment]
Strong agree. Have Low/Medium/High priority tags, and would be super nice to be able and properly color-code them

**Comment by BaldissaraMatheus** [comment]
Implemented by #65
