### ISSUE TITLE
The task file format

### ISSUE THREAD

**Issue by Djyp** [BaldissaraMatheus/Tasks.md#49]
It would be an interesting insight to find the file structure the app uses. If its file based then I may think of a way to sync it with Obsidian or any other markdown app.

Maybe just adding an example file with a few tasks would help to see the basic structure?

**Comment by BaldissaraMatheus** [comment]
The file structure is quite simple, basically every lane you add is a folder and every task is file.

So if you want to see the tasks in Obsidian, first you need to create a folder in your filesystem that will contain your files, then create a Tasks.md docker container with the volume `/api/files` mounted to that folder you just created, then sync your server with the device you're using Obsidian (I run Obsidian on my phone, so for that purpose I use syncting, but if you use the desktop app you could access this folder through Samba), then open the folder in Obsidian as a vault. The tasks will show up in Obsidian just like any other file, and creating files through there will also show up in Tasks.md just fine.

To show it as example, I just created a new docker container with the volume `/mnt/my-files/Tasks2:/api/files` and created a few lanes and one task.

So if your tasks look like this:
![image](https://github.com/BaldissaraMatheus/Tasks.md/assets/19363147/330ff8db-8d38-4980-aa0b-5698141695b2)

Your files will look like this:
![image](https://github.com/BaldissaraMatheus/Tasks.md/assets/19363147/ce2af22a-b9c3-4265-8763-013d2b4027d3)
![image](https://github.com/BaldissaraMatheus/Tasks.md/assets/19363147/94bba314-ac1d-427c-976d-58ac8678e0e9)

And in Obsidian you would see this:
![image](https://github.com/BaldissaraMatheus/Tasks.md/assets/19363147/c75ff98c-87b5-4840-9c24-fbb8fb10a168)

**Comment by Djyp** [comment]
This is perfect, you could copy-paste it in your project's documentation as is ! Now I know this format is not made for me ^^ I need to fork the project if I insist on using it.

Btw, it's totally working as is. I often have problems when I try to set up a project but this time it worked like a charm :heart:. I was able to use Tasks.md without tweaks or any hustle

**Comment by BaldissaraMatheus** [comment]
Great! I'm glad I could help. I'll update the documentation with that info as soon as possible
