### ISSUE TITLE
Allow arbitrary environment

### ISSUE THREAD

**Issue by orhtej2** [BaldissaraMatheus/Tasks.md#69]
While I understand target audience is supposed to run via Docker there's no technical reason why [the directory where data is stored](https://github.com/BaldissaraMatheus/Tasks.md/blob/ff736ef07a95e1444c0f9bc399361953e6486278/backend/server.js#L15C1-L16C75) and [port the app is listening on](https://github.com/BaldissaraMatheus/Tasks.md/blob/ff736ef07a95e1444c0f9bc399361953e6486278/backend/server.js#L315) are not sourced from `process.env`. 

This would allow bare metal hosting at no cost to app's maintainability.

**Comment by BaldissaraMatheus** [comment]
Yes, you're right. It requires a small change so I'll work on it as soon as possible

**Comment by BaldissaraMatheus** [comment]
Hey @orhtej2, I included this change in #73. Can you confirm if it works for you?

**Comment by BaldissaraMatheus** [comment]
This change was included by https://github.com/BaldissaraMatheus/Tasks.md/pull/73 so I'll close this issue. If someone thinks it's not working properly or could be improved, feel free to comment here and I'll open the issue again.

**Comment by orhtej2** [comment]
Hi, thanks for that, I did not have the time to test bare metal deployments
yet but the change looks OK!

TY for implementing this :)
