### ISSUE TITLE
Tasks saved in md keeps getting updated to rich text and that messes up the md file

### ISSUE THREAD

**Issue by accforgithubtest** [BaldissaraMatheus/Tasks.md#70]
I think this is potentially a very critical bug, as any task saved in markdown format is lost permanently.

To recreate the issue - 
* Create a new lane and add new task.
* Switch to the markdown format 
* Add a bunch of text in markdown
* Result-1 - The correct markdown file is saved

* Re-open the task in browser window.
* Defaults back to rich text mode, and this messes up the whole markdown text in the task details/description.
* Once you switch back into markdown, you are left with formatting issues, which is not markdown anymore.
* ISSUE: Only way to fix the text now is manually.

If possible, I recommend that the textbox always defaults to markdown, instead of richtext (given this is tasks.md afterall :) )

Sample

`First attempt at creating a new task - Initial File`
```
# Project Name

## Planning

* [ ] Add Ideas
* [ ] Groom backlog
* [ ] Track progress
```

`When re-opening the same task`
```
# Project Name

## Planning

* \[ \] Add Ideas
* \[ \] Groom backlog
* \[ \] Track progress
```

Once a task is re-opened in the browser, the md file is also auto-saved in the messed up format.

**Comment by BaldissaraMatheus** [comment]
Thanks for reporting the issue, I'm checking it right now. My guess is that Stacks Editor (the text editor we're using right now) doesn't support checkboxes. If that's the case I may consider replace it with a different editor, since using checkboxes for tasks is something very reasonable

**Comment by BaldissaraMatheus** [comment]
Thanks for reporting the issue, I'm checking it right now. My guess is that Stacks Editor (the text editor we're using right now) doesn't support checkboxes. If that's the case I may consider replace it with a different editor, since using checkboxes for tasks is something very reasonable. But in any case it shouldn't be escaping those characters.

About your suggestion of setting markdown mode as default, I think it makes sense and I'll create a new issue to track that and use this one for the bug you reported

**Comment by accforgithubtest** [comment]
> I may consider replace it with a different editor

Would something like shd101wyy/markdown-preview-enhanced be a good candidate ? 

I noticed it enables many other useful features like support for mermaid diagrams etc, So tasks.md will probably get a lot more functionality by using it.

**Comment by BaldissaraMatheus** [comment]
> Would something like shd101wyy/markdown-preview-enhanced be a good candidate ?

Sure, any suggestions are welcome. Though this one seems to be an extension for vscode, so not sure if it could be used here

**Comment by accforgithubtest** [comment]
ok, thanks for your reply. 

I am not a developer myself, but heard another developer colleague of mine mention that he is using shd101wyy/markdown-preview-enhanced in vscode and was raving about it. so I asked him to show it to me and thought I will share it here as well. Unfortunate that it is not something that can be used here.

**Comment by BaldissaraMatheus** [comment]
Just released a new version that sets the editor's default mode to Markdown mode and saves the user preference in the browser's local storage, so it will load the last used mode. This change was included by https://github.com/BaldissaraMatheus/Tasks.md/pull/78. 

The checkbox issue is being tracked on https://github.com/BaldissaraMatheus/Tasks.md/issues/76, so I'll close this one.

If it's not working properly or someone thinks it could be improved, feel free to comment here and I'll open the issue again
