### ISSUE TITLE
Only have access to .md files

### ISSUE THREAD

**Issue by uGeek** [BaldissaraMatheus/Tasks.md#74]
I have added my markdown notes directory (.md) to Task.md. In this directory there are configuration files from other note applications and Task.md reads these files as if they were cards.

Could you do that by means of a configuration file to limit that only the files of the extension that I decide (.md, .txt,...) are those that are seen as cards?

Currently this leads to errors, because if I have 600 .md files and there are 50 .jpg files, 20 .json files, Task.md will tell me that there are 670 cards when in fact there are only 600.

**Comment by BaldissaraMatheus** [comment]
Feature added by https://github.com/BaldissaraMatheus/Tasks.md/pull/78 and is present in the latest release, so I'll close the issue. If it's not working properly or someone thinks it could be improved, feel free to comment here and I'll open the issue again

**Comment by BaldissaraMatheus** [comment]
Feature added by https://github.com/BaldissaraMatheus/Tasks.md/pull/78 and is present in the latest release, so I'll close the issue. If it's not working properly or someone thinks it could be improved, feel free to comment here and I'll open the issue again

**Comment by uGeek** [comment]
I just tested it by copying .png files into the same directory as the .md files and it works great!!!! It only counts .md files. Thank you very much
