### ISSUE TITLE
Raspberry Pi 4 Support (docker)

### ISSUE THREAD

**Issue by o0mba0o** [BaldissaraMatheus/Tasks.md#8]
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

docker logs --follow tasks.md

exec /bin/sh: exec format error

**Comment by jk** [comment]
Just leave two links, to ease to creation of multi-arch docker images:

* Good and short introduction to build multi-arch images. There's all you need to build and push images in this article: https://www.thorsten-hans.com/how-to-build-multi-arch-docker-images-with-ease/
* If you want to automate multi-arch images with GitHub Actions, there is this article: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/ - a bit cumbersome to read

**Comment by BaldissaraMatheus** [comment]
#7 is going be merged very soon and will provide support for arm64 architetcture

**Comment by BaldissaraMatheus** [comment]
@o0mba0o The PR was merged, could you please pull the new image and test it again?

**Comment by BaldissaraMatheus** [comment]
@o0mba0o The PR was merged, could you please pull the new image and test it again?

**Comment by o0mba0o** [comment]
looks good. Thanks for the quick help.
