### ISSUE TITLE
It does not show any markdown files, if there is a subdirectory inside a column directory.

### ISSUE THREAD

**Issue by uGeek** [BaldissaraMatheus/Tasks.md#81]
Each directory we create corresponds to a column, but if we create a subdirectory inside a directory that belongs to a column, it doesn't show any files. 

Example:
If we have

- /tasks/Input/markdown_1.md
- /tasks/Input/note_2.md

In the input column it will show note_1 and note_2.

On the other hand if we create:
- /tasks/input/note_1.md
- /tasks/Input/note_2.md
- /tasks/input/new_folder/

It will not show any files in the column.

I think ideally it should show all .md files within the path /tasks/input/ or in that case, all files in the path /tasks/input/ and subdirectories. Ideally, I think it would show the ones in the /tasks/input/ path and discard the ones in other subdirectories. Currently if there are subdirectories, it doesn't show any .md files.

**Comment by BaldissaraMatheus** [comment]
Thanks for reporting the issue, it's fixed by #82. Let me know if it works for you!
