### ISSUE TITLE
cards not saving when certain characters are in the title

### ISSUE THREAD

**Issue by kuromad** [BaldissaraMatheus/Tasks.md#93]
I have noticed that once you use certain characters in the title of a card (like # \ ), it accepts the new name, and it is renamed in the file system. But all further modifications like editing content, renaming, moving lanes or deletion are not saved. It requires manual intervention to rename/remove those files to clean them up.

Perhaps a check and error message on the existence of those characters (and other characters disallowed in most filesystems) when renaming a card is a simple solution.

Thank you for your work. This tool makes my (work)life a lot easier.

**Comment by michaelborn** [comment]
Looks like this section of code that renames the card:

https://github.com/BaldissaraMatheus/Tasks.md/blob/main/backend/server.js#L173

could use some token replacement:

```js
const newName = (ctx.request.body.name || name)
  .replaceAll( /\s/g, '-' )
  .replaceAll(/[^a-z_-]/gi, '' )
  .replaceAll('--','-'); 
```

This converts something like: `"good, crazy / wild healthy food!"` to `"good-crazy-wild-healthy-food"`.

**Comment by AdrienCos** [comment]
> Looks like this section of code that renames the card:
> 
> [`main`/backend/server.js#L173](https://github.com/BaldissaraMatheus/Tasks.md/blob/main/backend/server.js?rgh-link-date=2024-04-23T12%3A50%3A59Z#L173)
> 
> could use some token replacement:
> 
> ```js
> const newName = (ctx.request.body.name || name)
>   .replaceAll( /\s/g, '-' )
>   .replaceAll(/[^a-z_-]/gi, '' )
>   .replaceAll('--','-'); 
> ```
> 
> This converts something like: `"good, crazy / wild healthy food!"` to `"good-crazy-wild-healthy-food"`.

I think that the third `replaceAll` function should be changed to :

```js
	.replaceAll(/-+/g, '-')
```

Otherwise, a `---` would only be replaced with `--` instead of a `-`.

I would also suggest choosing between dashes and underscores, to have a consistent file naming scheme.

**Comment by BaldissaraMatheus** [comment]
> Looks like this section of code that renames the card:
> 
> https://github.com/BaldissaraMatheus/Tasks.md/blob/main/backend/server.js#L173
> 
> could use some token replacement:
> 
> ```js
> const newName = (ctx.request.body.name || name)
>   .replaceAll( /\s/g, '-' )
>   .replaceAll(/[^a-z_-]/gi, '' )
>   .replaceAll('--','-'); 
> ```
> 
> This converts something like: `"good, crazy / wild healthy food!"` to `"good-crazy-wild-healthy-food"`.

I think it makes sense to keep white spaces as it makes it easier to read in the board. I'm preparing a new PR that includes a validation in the frontend app that prevents updating a card/lane name with [reserved characters](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions), so it won't even make a request to the API. It also includes a regex in this section to replace those characters, just in case

**Comment by michaelborn** [comment]
> I think it makes sense to keep white spaces as it makes it easier to read it in the board. 

Not attacking, just asking... why do filenames need to match the displayed title?

**Comment by BaldissaraMatheus** [comment]
> > I think it makes sense to keep white spaces as it makes it easier to read it in the board.
> 
> Not attacking, just asking... why do filenames need to match the displayed title?

I want it to feel like the cards and the files are the same thing as much possible, as the board was just a frontend view for them. Being this way makes it easy to navigate and makes it clear on how changing a file in one place affects it in the other one.

Also the app doesn't use any database, which means that if they were different we'd need to find way to map one thing to the other, so it's one less thing to worry about
