### ISSUE TITLE
Custom theme is not working

### ISSUE THREAD

**Issue by azzamsa** [BaldissaraMatheus/Tasks.md#96]
Hi, 👋

I've tried changing this line to use a different custom theme and even tried random string, but nothing changes. Not even an error message. I also restarted the container after each change.

```css
@import url(./color-themes/nord.css);
```

Am I missing something?

Thanks for Task.md 🍜

**Comment by BaldissaraMatheus** [comment]
I just tried creating a new container and changing this line from custom.css and it seems to be working fine. After updating this file try pressing ctrl + f5 on the browser to clear the cache, then let me know if it works

**Comment by azzamsa** [comment]
Tried to refresh multiple times and it doesn't work. 

```diff
-@import url(./color-themes/adwaita.css);
+@import url(./color-themes/random.css);
```

![image](https://github.com/BaldissaraMatheus/Tasks.md/assets/17734314/df1c0912-1527-4a15-bf9e-dfb57110f68b)

---

But after `Ctrl+f5` it works.
I think we need to add this browser cache thing to the readme https://github.com/BaldissaraMatheus/Tasks.md?tab=readme-ov-file#-customize. 
I am ready with a PR if you are okay.

![image](https://github.com/BaldissaraMatheus/Tasks.md/assets/17734314/1ffa1442-d6fb-45dd-a953-792e2d521fed)
![image](https://github.com/BaldissaraMatheus/Tasks.md/assets/17734314/2e72c6d9-c0ca-4aed-b3d9-c3b95a7ccd34)

**Comment by BaldissaraMatheus** [comment]
Sure, if you have a PR prepared feel free to submit it, then I'll review it soon. I agree that it should be pointed out in the docs
